[target.aarch64-linux-android]
linker = "C:\\Users\\g1169\\AppData\\Local\\Android\\Sdk\\ndk\\29.0.13599879\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android30-clang.exe"

[target.armv7-linux-androideabi]
linker = "C:\\Users\\g1169\\AppData\\Local\\Android\\Sdk\\ndk\\29.0.13599879\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi30-clang.exe"

[target.i686-linux-android]
linker = "C:\\Users\\g1169\\AppData\\Local\\Android\\Sdk\\ndk\\29.0.13599879\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\i686-linux-android30-clang.exe"

[target.x86_64-linux-android]
linker = "C:\\Users\\g1169\\AppData\\Local\\Android\\Sdk\\ndk\\29.0.13599879\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\x86_64-linux-android30-clang.exe" 